"""agrego role a usercredentials

Revision ID: a1784bf27b13
Revises: b2c45710e5a6
Create Date: 2025-11-13 21:43:41.593742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1784bf27b13'
down_revision = 'b2c45710e5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_credentials', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
